# ref: https://starship.rs/config/

"$schema" = "https://starship.rs/config-schema.json"

# inserts a blank line between shell prompts
add_newline = true

# prompt
[character]
success_symbol = "[»](bold green)"
error_symbol = "[»](bold red)"
